#!/bin/zsh

# Useful when creating new post.
# Usage: ./new

DIR="$(dirname "$(realpath "$0")")"

date=$(date +%Y-%m-%d)
time=$(date +%H:%M:%S)
date_time="$date $time"

echo "New post from $date_time.\n"

echo -n "Permalink name: "
read permalink

permalink=$(echo $permalink | sed "s/[ ]/-/g")
infile="$DIR/.post_template.md"
outfile="$DIR/_drafts/$date-$permalink.md"

# Check if any post with the same title exists.
if [ -f $outfile ]; then
    echo "$outfile already exists."
    exit 0
fi

echo -n "Title: "
read title

echo -n "Summary: "
read summary

echo -n "Categories (space separated): "
read categories

# Replace every space-padded string to "- (captured);".
# And then cut last character ';'.
# We use ';' to represent newline character.
# This suck happens because the newline character is a bit tricky to handle.
categories=$(echo $categories | sed "s/[ ]*\([^ ]*\)[ ]*/   - \1;/g" | sed "s/.$//")

content=$(cat $infile |
sed "s/__title__/$title/" |
sed "s/__summary__/$summary/" |
sed "s/__date_time__/$date_time/" |
sed "s/__categories__/$categories/" |
tr ';' '\n')

echo "\nPreview:"
echo $content

echo "Press enter to continue."
read

echo $content > $outfile
echo "New post created at $outfile."
